# Generated by Django 5.2 on 2025-12-07 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardia', '0001_initial'),
        ('sector', '0001_initial'),
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('clasificacion', models.CharField(choices=[('robo', 'Robo'), ('accidente', 'Accidente'), ('daño', 'Daño'), ('intento', 'Intento de delito'), ('otros', 'Otros')], max_length=20)),
                ('nivel_gravedad', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='incidentes_adjuntos/')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('investigacion', 'En investigación'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guardia.guardia')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sector.sector')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turno.turno')),
            ],
        ),
    ]
