# Generated by Django 6.0 on 2025-12-07 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id_guardia', models.AutoField(primary_key=True, serialize=False)),
                ('legajo', models.CharField(max_length=50, unique=True)),
                ('turno_habitual', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias', to='usuarios.usuario')),
            ],
        ),
    ]
