# Generated by Django 5.2.6 on 2025-12-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('guardia', 'Guardia')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
