# Generated by Django 6.0 on 2025-12-07 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardia', '0001_initial'),
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('ausente', 'Ausente')], default='programado', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='guardia.guardia')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='sector.sector')),
            ],
        ),
    ]
